config/routes.rb
Rails.application.routes.draw do
  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat rabbit snake turtle)
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  # GET /pets/
  def index
    @pets = Pet.all
  end # render "index.html.erb"

  # GET /pets/:id
  # ex: /pets/4
  def show
  end # render "show.html.erb"

  # GET /pets/new
  def new
    @pet = Pet.new
  end # render "new.html.erb"

  # POST /pets/
  # {"pet"=>{"name"=>"Garfield", "address"=>"Lyon", "species"=>"cat", "found_on"=>"2021-02-08"}}
  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end # No Render ! We have to redirect somewhere else

  # GET /pets/:id/edit
  def edit
  end # render "edit.html.erb"

  # PATCH /pets/:id
  # {"id" => "34", "pet"=>{"name"=>"Garfield", "address"=>"Lyon", "species"=>"cat", "found_on"=>"2021-02-08"}}
  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end # No render !

  # DELETE /pets/:id
  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%# form_for(pet) do |f| %>
  <%# f.label :name %>
  <%# f.text_field :name %>
  <%# f.label :address %>
  <%# f.text_field :address %>
  <%# f.label :species %>
  <%# f.select :species, Pet::SPECIES %>
  <%# f.label :found_on %>
  <%# f.date_field :found_on %>
  <%# f.submit %>
<%#end %>

<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on %>
<% end %>

app/views/pets/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h1>Edit <%= @pet.name %> </h1>
      <%= render 'form', pet: @pet %>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<h1>All found pets</h1>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to(pet.name, pet_path(pet)) %> (<%= pet.species %>)</li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>

<p>Species: <%= @pet.species %></p>

<p>Found on <%= @pet.found_on %> at <%= @pet.address %></p>

<%= link_to "Back to list", pets_path %>
<%= link_to "Edit", edit_pet_path(@pet) %>
<%= link_to "Delete #{@pet.name}", pet_path(@pet), method: :delete, data: { confirm: "Are you sure?" } %>